<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>4.7.0</Version>
        <AssemblyName>CrescentIsleUsefulTool</AssemblyName>
        <RootNamespace>CrescentIsleUsefulTool</RootNamespace>
        <Description>クレセントアイルの南征編・北征編向け総合探索支援ツール。</Description>
        <PackageProjectUrl>https://github.com/Rowsai/Crescent-Isle-Useful-Tool</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);4014</NoWarn>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)/</PathMap>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE;DEBUG_BUILD</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release_CN'">
        <DefineConstants>RELEASE;TRACE;DALAMUD_CN</DefineConstants>
    </PropertyGroup>
    <!-- Files -->
    <ItemGroup>
        <Content Include="..\assets\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <None Include="..\Translations\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Translations\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="..\Data\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="..\THIRD-PARTY-NOTICES.md">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>THIRD-PARTY-NOTICES.md</Link>
        </None>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Dependencies\Ocelot\Ocelot.csproj" />
        <PackageReference Include="Pictomancy" Version="1.0.3" />
        <PackageReference Include="TextCopy" Version="6.2.1" />
    </ItemGroup>
</Project>
